name: transport
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1


environment:

  sdk: ">=2.16.1 <3.0.0"

  #sdk: '>=2.12.0 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the lates t versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  google_maps_flutter: ^2.1.8
  flutter_google_places: ^0.3.0
  google_maps_webservice: ^0.0.19
  provider: ^6.0.2
  sqflite: ^2.0.2+1
  path: ^1.8.1
  permission_handler: ^10.2.0
  syncfusion_flutter_charts: ^20.1.52
  flutter_sound: ^9.2.13
  audioplayers: ^0.19.0
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  geolocator: ^9.0.2
  geocoding: ^2.0.4
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  google_sign_in: ^5.3.3
  sign_in_with_apple: ^4.2.0
  flutter_facebook_auth: ^5.0.6
  jwt_decoder: ^2.0.1
  http: ^0.13.4
  change_app_package_name: ^1.1.0
  flutter_polyline_points: ^1.0.0
  location: ^4.2.0
  material_design_icons_flutter: ^6.0.7096
  audio_session: ^0.1.10
  shared_preferences: ^2.0.7 # 本地存储 -- 实现主题持久化

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/data_107_1.json
    - assets/data_108_1.json
    - assets/data_109_1.json
    - assets/data_110_1.json
    - assets/data_107_2.json
    - assets/data_108_2.json
    - assets/data_109_2.json
    - assets/data_110_2.json
    - assets/data_107_3.json
    - assets/data_108_3.json
    - assets/data_109_3.json
    - assets/data_110_3.json
    - assets/data_107.json
    - assets/data_108.json
    - assets/data_109.json
    - assets/data_110.json
    - assets/audio_1.mp3
    - assets/audio_2.mp3   
    - assets/audio_3.mp3   
    - assets/audio_4.mp3       
    - assets/audio_5.mp3
    - assets/audio_6.mp3   
    - assets/audio_7.mp3   
    - assets/audio_8.mp3     
    - assets/audio_9.mp3
    - assets/audio_10.mp3   
    - assets/audio_11.mp3   
    - assets/audio_12.mp3     
    - assets/audio_13.mp3
    - assets/audio_14.mp3   
    - assets/audio_15.mp3   
    - assets/audio_16.mp3     
    - assets/audio_17.mp3     
    - assets/die_people.json
    - assets/test.mp3
    - assets/turn-left.png
    - assets/turn-right.png
    - assets/uturn-left.png
    - assets/uturn-right.png
    - assets/straight.png
    - assets/MapIcon.png
    - assets/cross2.png
    - assets/turn-left.mp3
    - assets/turn-right.mp3
    - assets/uturn-left.mp3
    - assets/uturn-right.mp3
    - assets/early-turn-left.mp3
    - assets/early-turn-right.mp3
    - assets/early-uturn-left.mp3
    - assets/early-uturn-right.mp3
    - assets/circle_point.png
    - assets/moto.png
    - assets/moto_3.png
    - assets/car.png
    - assets/person.png
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
